# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read basis operators in binary representation from input file.
#' 
#' Reads the Basis operators in binary representation from the given input 
#' file. The operators should be written in one single column and as 
#' binary representation of the spin involved in the Operator. Returns a 
#' list of the basis with the integer value of that binary representation
#' 
#' @param Basis_binary_filename The name of input file including path.
#' @param n Number of binary (spin) variables of the data set.
#' 
#' @return Basis_li List of the basis with the integer value of that binary representation.
#' 
#' @export
Read_BasisOp_BinaryRepresentation <- function(Basis_binary_filename, n) {
    .Call(`_MinCompSpinPackage_Read_BasisOp_BinaryRepresentation`, Basis_binary_filename, n)
}

#' Read basis operators in integer representation from input file.
#' 
#' Reads the Basis operators in integer representation from the given input 
#' file. The operators should be written in one single column and as the
#' integer value of that binary representation. Returns a 
#' list of the given input file.
#' 
#' @param Basis_integer_filename The name of input file including path.
#' 
#' @return Basis_li List of the given input file.
#' 
#' @export
Read_BasisOp_IntegerRepresentation <- function(Basis_integer_filename) {
    .Call(`_MinCompSpinPackage_Read_BasisOp_IntegerRepresentation`, Basis_integer_filename)
}

#' Original Basis
#' 
#' Return the original basis, i.e., {s1, s2, ..., sn}
#' 
#' @param n Number of binary (spin) variables of the data set.
#' 
#' @return Basis_li List of the original basis i.e. {s1, s2, ..., sn}.
#' 
#' @export
Original_Basis <- function(n) {
    .Call(`_MinCompSpinPackage_Original_Basis`, n)
}

#' Print Basis
#' 
#' Print the basis info in the terminal.
#' 
#' @param Basis_li A list containing the basis.
#' @param n Number of binary (spin) variables of the data set.
#' 
#' @export
PrintTerm_Basis <- function(Basis_li, n) {
    invisible(.Call(`_MinCompSpinPackage_PrintTerm_Basis`, Basis_li, n))
}

#' MCM_GivenRank_r
#' 
#' Compare all the MCM of rank r,
#' based on the r first elements of the basis used to build Kset:
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param N The size of the data-set.
#' @param LogE_best The double which will contain the maximized Log-evidence.
#' @param r The rank r which is the r first elements of the basis.
#' @param n The amount of binary (spin) variables.
#' @param OUTPUT_directory The name of the output directory (and path to it) in which to save the output data. 
#' @param print_bool Boolean to print related information to terminal. Default: FALSE.
#' 
#' @return Partition The best MCM.
#' 
#' @export
MCM_GivenRank_r <- function(Kset, N, LogE_best, r, n, OUTPUT_directory, print_bool) {
    .Call(`_MinCompSpinPackage_MCM_GivenRank_r`, Kset, N, LogE_best, r, n, OUTPUT_directory, print_bool)
}

#' MCM_AllRank_SmallerThan_r_Ordered
#' 
#' Compare all the MCM 
#' based on the k first elements of the basis used to build Kset
#' for all k=1 to r, where r <= basis.size().
#' By default: - r=n
#'             - the function doesn't print the logE-values for all the tested MCMs. To activate --> print_bool = true
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param N The size of the data-set.
#' @param LogE_best The double which will contain the maximized Log-evidence.
#' @param r The rank r which is the r first elements of the basis.
#' @param n The amount of binary (spin) variables.
#' @param OUTPUT_directory The name of the output directory (and path to it) in which to save the output data. 
#' @param print_bool Boolean to print related information to terminal. Default: FALSE.
#' 
#' @return Partition The best MCM.
#' 
#' @export
MCM_AllRank_SmallerThan_r_Ordered <- function(Kset, N, LogE_best, r, n, OUTPUT_directory, print_bool) {
    .Call(`_MinCompSpinPackage_MCM_AllRank_SmallerThan_r_Ordered`, Kset, N, LogE_best, r, n, OUTPUT_directory, print_bool)
}

#' MCM_AllRank_SmallerThan_r_Ordered
#' 
#' Compare all the MCMs based on any subset of k elements
#' of the of r first elements of the basis used to build Kset
#' for all k=1 to r, where r <= basis.size()
#' By default: - r=n
#'             - the function doesn't print the logE-values for all the tested MCMs. To activate --> print_bool = true
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param N The size of the dataset
#' @param LogE_best The double which will contain the maximized Log-evidence.
#' @param r The rank r which is the r first elements of the basis.
#' @param n The amount of binary (spin) variables.
#' @param OUTPUT_directory The name of the output directory (and path to it) in which to save the output data. 
#' @param print_bool Boolean to print related information to terminal. Default: FALSE.
#' 
#' @return Partition The best MCM.
#' 
#' @export
MCM_AllRank_SmallerThan_r_nonOrdered <- function(Kset, N, LogE_best, r, n, OUTPUT_directory, print_bool) {
    .Call(`_MinCompSpinPackage_MCM_AllRank_SmallerThan_r_nonOrdered`, Kset, N, LogE_best, r, n, OUTPUT_directory, print_bool)
}

#' GeomComplexity_SubCM
#' 
#' Geometric Complexity of a Sub-Complete Model based on m basis operators.
#' for 1 <= m <= n . Rem C(m=1) = log(pi)
#' 
#' @param m The number of basis elements/operators.
#' 
#' @return GeomComplexity The complexity.
#' 
#' @export
GeomComplexity_SubCM <- function(m) {
    .Call(`_MinCompSpinPackage_GeomComplexity_SubCM`, m)
}

#' Parametric Complexity of a sub-complete model
#' 
#' Parametric Complexity of a Sub-Complete Model based on m basis operators.
#' for 1 <= m <= n . Rem C(m=1) = log(pi).
#' 
#' @param m The number of basis elements/operators.
#' @param N The size of the data-set.
#' 
#' @return ParamComplexity The complexity.
#' 
#' @export
ParamComplexity_SubCM <- function(m, N) {
    .Call(`_MinCompSpinPackage_ParamComplexity_SubCM`, m, N)
}

#' Complexity of an MCM based on the geometric and parametric complexity.
#' 
#' Complexity of and MCM defined by the addition of the total geometric complexity and
#' total (parametric) first order complexity. 
#' Compute separately: -- the first order complexity    --> stored in C_param
#'                     -- and the geometric complexity  --> stored in C_geom 
#' 
#' @param Partition Partition of MCM.
#' @param N The size of the dataset
#' @param n The amount of spin variables.
#' @param C_param The (parametric) first order complexity.
#' @param C_geom The geometric complexity.
#' 
#' @return Complexity A double containing the complexity of the MCM.
#' 
#' @export
Complexity_MCM <- function(Partition, N, n, C_param, C_geom) {
    .Call(`_MinCompSpinPackage_Complexity_MCM`, Partition, N, n, C_param, C_geom)
}

#' Read data and store in Nset.
#' 
#' Reads the binary data set (with location and name provided in argument filename) 
#' as binary integers and returns a mapping of each observed state to the number of times 
#' they occur in the data set. Note that each state of the system is encoded as an n-bit integer.
#' 
#' @param N Integer that will contain the data set size.
#' @param n Number of binary (spin) variables of the data set.
#' @param filename The string containing the path to the data file and the name.
#' 
#' @return Nset The first row contains the observed state and the second row contains their occurrence (matching column-wise).
#' 
#' @export
read_datafile <- function(N, n, filename) {
    .Call(`_MinCompSpinPackage_read_datafile`, N, n, filename)
}

#' Build K_set
#' 
#' Build Kset for the states written in the basis of the m-chosen independent 
#' operator on which the SC model is based. Changes the basis of the data-set from its original basis
#' to the basis provided as an argument in basis. Print Kset to terminal by setting print_bool to TRUE.
#' 
#' @param Nset A list containing 2 vectors which correspond to a index based mapping of the states in the data set to their occurrence.
#' @param Basis The basis on which the model is based. 
#' @param n Number of binary (spin) variables of the data set.
#' @param print_bool print relevant information. Default: FALSE.
#' 
#' @return Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' 
#' @export
build_Kset <- function(Nset, Basis, n, print_bool = FALSE) {
    .Call(`_MinCompSpinPackage_build_Kset`, Nset, Basis, n, print_bool)
}

#' Compute the log-evidence of the sub-complete part (of an MCM).
#' 
#' Compute the log-evidence of the sub-complete part (of an MCM) defined by Ai.
#' This function could be also used directly by the user
#' to compute the log-likelihood of a sub-complete model
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param Ai The binary representation of the sub-complete part (of an MCM).
#' @param N The size of the data-set.
#' @param n The amount of binary (spin) variables.
#' @param print_bool Boolean to print related information to terminal. Default: FALSE.
#' 
#' @return LogE The log-evidence of the sub-complete part (of an MCM) as a double.
#' 
#' @export
LogE_SubCM <- function(Kset, Ai, N, n, print_bool = FALSE) {
    .Call(`_MinCompSpinPackage_LogE_SubCM`, Kset, Ai, N, n, print_bool)
}

#' Compute the log-evidence of of an MCM.
#' 
#' Compute the log-evidence of of an MCM.
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param Partition Partition of MCM.
#' @param N The size of the data-set.
#' @param n The amount of binary (spin) variables.
#' @param print_bool Boolean to print related information to terminal. Default: FALSE.
#' 
#' @return LogE The log-evidence of an MCM as a double.
#' 
#' @export
LogE_MCM <- function(Kset, Partition, N, n, print_bool = FALSE) {
    .Call(`_MinCompSpinPackage_LogE_MCM`, Kset, Partition, N, n, print_bool)
}

#' Compute the log-likelihood of a complete model on Kset.
#' 
#' Compute the log-likelihood of a complete model on Kset:
#' This function is mainly used for call by `LogL_SC_PartMCM`,
#' but can also be used to compute the log-likelihood of a complete model
#' 
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param N The size of the data-set.
#' 
#' @return LogL The log-likelihood of a complete model on Kset as a double.
#' 
#' @export
LogL_CM <- function(Kset, N) {
    .Call(`_MinCompSpinPackage_LogL_CM`, Kset, N)
}

#' Compute log-likelihood of the sub-complete part (SC-part) of an MCM.
#' 
#' Compute the log-likelihood of the sub-complete part (of an MCM) defined by Ai.
#' This function could be also used directly by the user to compute the 
#' log-likelihood of a sub-complete model
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param Ai The binary representation of the SC-part.
#' @param N The size of the data-set.
#' @param n Number of binary (spin) variables of the data set.
#' @param print_bool Boolean to print related information to terminal. Default: FALSE.
#' 
#' @return LogL The log-likelihood of a sub-complete part (of an MCM) defined by Ai.
#' 
#' @export
LogL_SubCM <- function(Kset, Ai, N, n, print_bool = FALSE) {
    .Call(`_MinCompSpinPackage_LogL_SubCM`, Kset, Ai, N, n, print_bool)
}

#' Compute log-likelihood of an MCM.
#' 
#' Compute the log-likelihood of of an MCM.
#' This function could be also used directly by the user
#' to compute the log-likelihood of a model.
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param Partition Partition of MCM.
#' @param N The size of the data-set.
#' @param n Number of binary (spin) variables of the data set.
#' @param print_bool Boolean to print related information to terminal. Default: FALSE.
#' 
#' @return LogL The log-likelihood of a complete model on Kset as a double.
#' 
#' @export
LogL_MCM <- function(Kset, Partition, N, n, print_bool = FALSE) {
    .Call(`_MinCompSpinPackage_LogL_MCM`, Kset, Partition, N, n, print_bool)
}

#' Define an MCM
#' 
#' Define an MCM. Input is an integer representation of all MCM parts. For example, 
#' MCM_Choice = c(384, 64, 32, 16, 8, 4, 2, 1) defines an MCM with 8 independent parts, 
#' based on n=9 spins. You can check that the model (i.e., list of parts) that you have 
#' provided properly defines an MCM by calling the function check_partition(Partition, n).
#' 
#' @param MCM_table List containing the integer representation of the MCM parts. 
#' 
#' @return MCM_partition The defined MCM.
#' 
#' @export
Create_MCM <- function(MCM_table) {
    .Call(`_MinCompSpinPackage_Create_MCM`, MCM_table)
}

#' Read_MCMParts_BinaryRepresentation
#' 
#' Define MCM from a file in which the operators are written as the binary 
#' representation of the interactions.
#' 
#' @param MCM_binary_filename The file name (incl. the path to it from the current directory).
#' @param n The amount of binary (spin) variables.
#' 
#' @return MCM_partition The defined MCM.
#' 
#' @export
Read_MCMParts_BinaryRepresentation <- function(MCM_binary_filename, n) {
    .Call(`_MinCompSpinPackage_Read_MCMParts_BinaryRepresentation`, MCM_binary_filename, n)
}

#' check_partition
#' 
#' Check if *Partition* is an actual partition of r basis elements,
#' i.e., that no basis element appears in more than 1 part of the partition.
#' i.e., that each basis element only appears in a single part of the partition.
#' 
#' @param Partition Partition of MCM.
#' @param n The amount of binary (spin) variables.
#' 
#' @return Bool_results Returns FALSE if there is an overlap between the parts.
#' 
#' @export
check_partition <- function(Partition, n) {
    .Call(`_MinCompSpinPackage_check_partition`, Partition, n)
}

#' PRINT INFO on each PART of an MCM (= a partition)
#' 
#' The function prints the number of Independent Components of the MCM 
#' (i.e., the number of partitions -- or communities -- of the MCM),
#' as well as the log-likelihood (LogL), the parameter complexity (C_param), 
#' the geometric complexity (C_geom), the total complexity (C_tot), 
#' the Minimum Description Length (MDL) and the log-evidence (LogE). 
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param N The size of the data-set.
#' @param n The amount of binary (spin) variables.
#' @param MCM_Partition Partition of MCM.
#' 
#' @export
PrintTerminal_MCM_Info <- function(Kset, N, n, MCM_Partition) {
    invisible(.Call(`_MinCompSpinPackage_PrintTerminal_MCM_Info`, Kset, N, n, MCM_Partition))
}

#' PRINT INFO ON SUCCESSIVE INDEPENDENT MODELS IN THE NEW BASIS.
#' 
#' The function prints the integer and binary representation of the part 
#' , as well as the the log-likelihood (LogL) and the log-evidence (LogE).
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param N The size of the data-set.
#' @param n The amount of binary (spin) variables.
#'  
#' @export
PrintInfo_All_Indep_Models <- function(Kset, N, n) {
    invisible(.Call(`_MinCompSpinPackage_PrintInfo_All_Indep_Models`, Kset, N, n))
}

#' PrintInfo_All_Indep_Models
#' 
#' PRINT INFO ON SUCCESSIVE SUB_COMPLETE MODELS IN THE NEW BASIS.
#' 
#' @param Kset Mapping of frequency of occurrence of each state of the data-set in the new basis.
#' @param N The size of the data-set.
#' @param n The amount of binary (spin) variables.
#' 
#' @export
PrintInfo_All_SubComplete_Models <- function(Kset, N, n) {
    invisible(.Call(`_MinCompSpinPackage_PrintInfo_All_SubComplete_Models`, Kset, N, n))
}

#' Perform the exhaustive search for the best MCM at once.
#' 
#' Performs the community detection on the data given in datafilename with the given basis Basis_li 
#' and returns the best fitting MCM for the data. Optional: set the comparison
#' variable to TRUE to test what happens when the model is compared to 3 different cases.
#' For general use set to FAlSE. Output is stored in the (newly created)
#' OUTPUT directory in the same working directory.
#' 
#' @param n Number of binary (spin) variables of the data set.
#' @param datafilename The name of input file including path containing the binary data.
#' @param Basis_li The basis on which the model is based. 
#' @param OUTPUT_directory The name of the output directory (and path to it) in which to save the output data. 
#' @param comparison Boolean indicating whether to run 2 other versions of the exhaustive search. For comparison purposes. Default: FALSE. 
#' 
#' @export
MCM_search <- function(n, datafilename, Basis_li, OUTPUT_directory, comparison) {
    .Call(`_MinCompSpinPackage_MCM_search`, n, datafilename, Basis_li, OUTPUT_directory, comparison)
}

